### ISSUE TITLE
@TODO Error:

### ISSUE THREAD

**Issue by EV451ca** [jamesbachini/FriendTech-Trading-Bot#1]
i have this error. 
  what can i do with that?
  @TODO Error: could not coalesce error (error={ "code": -32000, "message": "filter not found" }, payload={ "id": 12, "jsonrpc": "2.0", "method": "eth_getFilterChanges", "params": [ "0x62ec0aef135b9502c871d195b54c943e" ] }, code=UNKNOWN_ERROR, version=6.7.1)
    at makeError (C:\Users\EVZAG\Desktop\FriendTech-Trading-Bot-main\node_modules\ethers\lib.commonjs\utils\errors.js:125:21)
    at JsonRpcProvider.getRpcError (C:\Users\EVZAG\Desktop\FriendTech-Trading-Bot-main\node_modules\ethers\lib.commonjs\providers\provider-jsonrpc.js:653:41)
    at C:\Users\EVZAG\Desktop\FriendTech-Trading-Bot-main\node_modules\ethers\lib.commonjs\providers\provider-jsonrpc.js:268:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: { code: -32000, message: 'filter not found' },
  payload: {
    method: 'eth_getFilterChanges',
    params: [ '0x62ec0aef135b9502c871d195b54c943e' ],
    id: 12,
    jsonrpc: '2.0'
  }

**Comment by jamesbachini** [comment]
Maybe try a different ROC node?

**Comment by 0xAkephalos** [comment]
I used a WSS endpoint instead of an RPC endpoint. That resolved the issue.

https://docs.base.org/tools/node-providers/

**Comment by ETHSev** [comment]
i Cant resolve the problem of :
}
@TODO Error: could not coalesce error (error={ "code": -32000, "message": "filter not found" }, payload={ "id": 12, "jsonrpc": "2.0", "method": "eth_getFilterChanges", "params": [ "0x8362aced65e82d2ea696367cffc4d5a4" ] }, code=UNKNOWN_ERROR, version=6.7.1)
    at makeError (/mnt/c/Users/nezar/OneDrive/Escritorio/Bot/FriendTech-Trading-Bot/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at JsonRpcProvider.getRpcError (/mnt/c/Users/nezar/OneDrive/Escritorio/Bot/FriendTech-Trading-Bot/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:653:41)
    at /mnt/c/Users/nezar/OneDrive/Escritorio/Bot/FriendTech-Trading-Bot/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:268:45
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'UNKNOWN_ERROR',
  error: { code: -32000, message: 'filter not found' },
  payload: {
    method: 'eth_getFilterChanges',
    params: [ '0x8362aced65e82d2ea696367cffc4d5a4' ],
    id: 12,
    jsonrpc: '2.0'
  }
}
