### ISSUE TITLE
@Todo 

### ISSUE THREAD

**Issue by DikaCream** [jamesbachini/FriendTech-Trading-Bot#2]
Getting error even we try different RPC 

@todo Error: could not coalesce error (error={ "code": -32000, "message": "filter not found" }, payload={ "id": 12, "jsonrpc": "2.0", "method": "eth_getFilterChanges", "params": [ "0x62ec0aef135b9502c871d195b54c943e" ] }, code=UNKNOWN_ERROR, version=6.7.1)
at makeError (C:\Users\EVZAG\Desktop\FriendTech-Trading-Bot-main\node_modules\ethers\lib.commonjs\utils\errors.js:125:21)
at JsonRpcProvider.getRpcError (C:\Users\EVZAG\Desktop\FriendTech-Trading-Bot-main\node_modules\ethers\lib.commonjs\providers\provider-jsonrpc.js:653:41)
at C:\Users\EVZAG\Desktop\FriendTech-Trading-Bot-main\node_modules\ethers\lib.commonjs\providers\provider-jsonrpc.js:268:45
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'UNKNOWN_ERROR',
error: { code: -32000, message: 'filter not found' },
payload: {
method: 'eth_getFilterChanges',
params: [ '0x62ec0aef135b9502c871d195b54c943e' ],
id: 12,
jsonrpc: '2.0'

What should I do ?

**Comment by 0xAkephalos** [comment]
I used a WSS endpoint instead of an RPC endpoint. That resolved the issue.

https://docs.base.org/tools/node-providers/
