### ISSUE TITLE
@TODO Error

### ISSUE THREAD

**Issue by CrumpledGlitch** [jamesbachini/FriendTech-Trading-Bot#4]
@TODO Error: could not coalesce error (error={ "code": -32000, "message": "filter not found" }, payload={ "id": 17, "jsonrpc": "2.0", "method": "eth_getFilterChanges", "params": [ "0xd578d4ba30058b2fcca34d3e2d5c8f41" ] }, code=UNKNOWN_ERROR, version=6.7.1)
    at makeError (/mnt/f/FriendTech-Trading-Bot/node_modules/ethers/lib.commonjs/utils/errors.js:125:21)
    at JsonRpcProvider.getRpcError (/mnt/f/FriendTech-Trading-Bot/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:653:41)
    at /mnt/f/FriendTech-Trading-Bot/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:268:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: { code: -32000, message: 'filter not found' },
  payload: {
    method: 'eth_getFilterChanges',
    params: [ '0xd578d4ba30058b2fcca34d3e2d5c8f41' ],
    id: 17,
    jsonrpc: '2.0'
  }
}

**Comment by CrumpledGlitch** [comment]
Changed provider
